version: '3.8'

services:
    server:
        image: node:16-alpine3.11
        container_name: server
        depends_on: ['mysql']
        volumes:
            - './:/app'
        working_dir: /app
        ports:
            - '3000:3000'
        command:
            - /bin/sh
            - -c
            - |
                npm i
                npm run dev

    mysql:
        image: mysql:8.0.27
        container_name: database
        ports:
            - '3306:3306'
        volumes:
            - 'dbdata:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: password

volumes:
    dbdata: {}